### ISSUE TITLE
What if you don’t want to use bootstrap binding for each form?

### ISSUE THREAD

**Issue by bebraw** [MadRabbit/a-plus-forms-bootstrap#1]
Title gets to the point. All it takes is one exception in someone’s app. :)

**Comment by kaievns** [comment]
Than they can use the `LayoutProvider` and specify different layouts for different sections of an app. Also, you can set the `layout` prop on a specific `Form` if you need that form to be rendered with something special.

check this doc's "Layouts Usage" section for more details https://github.com/MadRabbit/a-plus-forms/wiki/Layouts-&-Styling

**Comment by bebraw** [comment]
Makes sense. Thanks. 👍
